name: 'ESLint Reporter'
author: Rafi Rahman
description: 'Generate Markdown formatted reports from JSON formatted ESLint linting results.'
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  eslint-json:
    description: 'ESLint results JSON'
    required: true
  title:
    description: Title to use for report'
    required: true
    default: 'ESLint Report'
outputs:
  report:
    description: 'Markdown formatted report'
runs:
  using: 'node16'
  main: 'dist/index.js'
